version: '3'

services:
  registry:
    image: registry:latest
    ports:
    - "5000:5000"
    - "443:443"
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      - /var/registry:/var/lib/registry
      - /etc/letsencrypt/live/domain.example.com:/certs